### ISSUE TITLE
Please support compiling on on red hat based distributions !

### ISSUE THREAD

**Issue by ytrezq** [ROIcoin/ROIcoin#1]
Unlike Ubuntu Fedora has a port for ᴀʀᴍ. So I’m using ᴀʀᴍ port of Fedora for compiling natively.
Most errors are build-script errors, and I’m really stuck on that one :

    LC_ALL=C make
    Making all in src
    make[1]: Entering directory '/home/example/sources/app/ROIcoin/src'
    make[2]: Entering directory '/home/example/sources/app/ROIcoin/src'
    make[3]: Entering directory '/home/example/sources/app/ROIcoin/src/secp256k1'
    Makefile:3095: *** missing separator.  Stop.
    make[3]: Leaving directory '/home/example/sources/app/ROIcoin/src/secp256k1'
    make[2]: *** [Makefile:7108: secp256k1/libsecp256k1.la] Error 2
    make[2]: Leaving directory '/home/example/sources/app/ROIcoin/src'
    make[1]: *** [Makefile:6614: all-recursive] Error 1
    make[1]: Leaving directory '/home/example/sources/app/ROIcoin/src'
    make: *** [Makefile:643: all-recursive] Error 1

and inside the autotools generated Makefile, everything looks correct :

    include test/$(DEPDIR)/test_test_ROIcoin-main_tests.Po
    include test/$(DEPDIR)/test_test_ROIcoin-mempool_tests.Po
    include test/$(DEPDIR)/test_test_ROIcoin-miner_tests.Po
    include test/$(DEPDIR)/test_test_ROIcoin-mruset_tests.Po
    include test/$(DEPDIR)/test_test_ROIcoin-multisig_tests.Po
    include test/$(DEPDIR)/test_test_ROIcoin-netbase_tests.Po
    include test/$(DEPDIR)/test_test_ROIcoin-pmt_tests.Po
    include test/$(DEPDIR)/test_test_ROIcoin-policyestimator_tests.Po
    include test/$(DEPDIR)/test_test_ROIcoin-pow_tests.Po
    include test/$(DEPDIR)/test_test_ROIcoin-reverselock_tests.Po
    include test/$(DEPDIR)/test_test_ROIcoin-rpc_tests.Po
    include test/$(DEPDIR)/test_test_ROIcoin-rpc_wallet_tests.Po
    include test/$(DEPDIR)/test_test_ROIcoin-sanity_tests.Po
    include test/$(DEPDIR)/test_test_ROIcoin-scheduler_tests.Po
    include test/$(DEPDIR)/test_test_ROIcoin-script_P2SH_tests.Po
    include test/$(DEPDIR)/test_test_ROIcoin-script_tests.Po
    include test/$(DEPDIR)/test_test_ROIcoin-scriptnum_tests.Po
    include test/$(DEPDIR)/test_test_ROIcoin-serialize_tests.Po
    include test/$(DEPDIR)/test_test_ROIcoin-sighash_tests.Po
    include test/$(DEPDIR)/test_test_ROIcoin-sigopcount_tests.Po
    include test/$(DEPDIR)/test_test_ROIcoin-skiplist_tests.Po
    include test/$(DEPDIR)/test_test_ROIcoin-test_roicoin.Po
    include test/$(DEPDIR)/test_test_ROIcoin-timedata_tests.Po
    include test/$(DEPDIR)/test_test_ROIcoin-transaction_tests.Po
    include test/$(DEPDIR)/test_test_ROIcoin-uint256_tests.Po
    include test/$(DEPDIR)/test_test_ROIcoin-univalue_tests.Po
    include test/$(DEPDIR)/test_test_ROIcoin-util_tests.Po
    include univalue/$(DEPDIR)/univalue.Po
    include univalue/$(DEPDIR)/univalue_read.Po
    include univalue/$(DEPDIR)/univalue_write.Po
    include wallet/$(DEPDIR)/libroicoin_wallet_a-crypter.Po
    include wallet/$(DEPDIR)/libroicoin_wallet_a-db.Po
    include wallet/$(DEPDIR)/libroicoin_wallet_a-rpcdump.Po
    include wallet/$(DEPDIR)/libroicoin_wallet_a-rpcwallet.Po
    include wallet/$(DEPDIR)/libroicoin_wallet_a-wallet.Po
    include wallet/$(DEPDIR)/libroicoin_wallet_a-wallet_ismine.Po
    include wallet/$(DEPDIR)/libroicoin_wallet_a-walletdb.Po
    include wallet/test/$(DEPDIR)/test_test_ROIcoin-wallet_tests.Po

    .cc.o:
    @am__fastdepCXX_TRUE@<->$(AM_V_CXX) depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
    @am__fastdepCXX_TRUE@<->$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
    @am__fastdepCXX_TRUE@<->$(am__mv) $$depbase.Tpo $$depbase.Po
    @am__fastdepCXX_FALSE@<>$(AM_V_CXX)source='$<' object='$@' libtool=no \
    @am__fastdepCXX_FALSE@<>DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
    @am__fastdepCXX_FALSE@<>$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

**Comment by ytrezq** [comment]
Hey why did you close it? On Fedora everything je récent. But different paths structures make this a Hell.

It is far from being fixed. The daemon is not enough for all functions. I need graphical interface.

**Comment by ghobson2013** [comment]
Hi, 

here are the build instructions i used to build on fedora 27
https://github.com/ROIcoin/ROIcoin/blob/development/doc/build-fedora27.txt

**Comment by ghobson2013** [comment]
i added the binaries on the release page https://github.com/ROIcoin/ROIcoin/releases/tag/v1.1.0.000

**Comment by ghobson2013** [comment]
Please let me know if this is working for you.

**Comment by ghobson2013** [comment]
I have provided the build instructions for fedora 27, closing this issue
