### ISSUE TITLE
Term Deposit Documentation needed

### ISSUE THREAD

**Issue by TheTDD** [ROIcoin/ROIcoin#10]
Can you please describe how the create the term deposit transactions using the ROIcoin-cli, without need to start the QT wallet (createrawtransaction?). That will give the possibilities to create term deposit using shell scripts automatically based on incoming coins. Open the wallet every day to just send new arrived coins to deposit is boring.

**Comment by ROIcoin** [comment]
These are functions within the QT wallet (coin control, deposits, etc..).  The CLI is used to pass standard RPC commands to the ROIcoind.  I will confer with my associates as I am not personally aware of CLI being used in this regard, therefore, I could be missing something.  Thank you for your patience.

**Comment by ghobson2013** [comment]
Someone asked for the same thing on Hodlcoin, 
There is currently no way to do this, i am marking this as an enhancement request.

**Comment by TheTDD** [comment]
Is it possible to create new daemon command the same way as "sendtoaddress"?

> deposit "roicoinaddress" amount numberofblocks subtractfeefromamount

If deposit can be created in QT there should be the way to copy the code into the daemon.

**Comment by ghobson2013** [comment]
http://oi65.tinypic.com/5vrwqe.jpg screenshot of listtermdeposits RPC call

**Comment by ghobson2013** [comment]
v1.1.5 has been released. closing this issue.
