### ISSUE TITLE
win64 assert error when mining with AVX2

### ISSUE THREAD

**Issue by ghobson2013** [ROIcoin/ROIcoin#11]
Reported by maxente on BCT, 

When solo mining on windows 64 on AMD Athlon X4, he gets an assert on miner.cpp line 614 ( hash.GetHex() == pBlock->GetHash().GetHex() ).

**Comment by ghobson2013** [comment]
FuzzBawls is the one who backported the Optiminer changes in hodlminer into the hodlcoin wallet ( solo miner ).
source reference: https://github.com/HOdlcoin/HOdlcoin/commit/56b2cd833b90e1a474153976853e5f03a84ba28f

I tested the following combinations:
hodlcoin 3.0.1 - intel i7 with aes and avx2 ,throws an assert on miner.cpp line 614 ( hash.GetHex() == pBlock->getHash().GetHex())  fails to pass verification function.
hodlcoin 3.0.1 - intel i5 with aes and avx2 , same exact error.
I don't have AMD cpu so can't test it, but i will assume it will have same issues.

Since we forked from hodlcoin we see same issue, I can only conclude the backport from hodlminer was not fully portable.
Note: on Linux it works fine, so this is a windows 64bit specific problem.

I will try and see if I can find the reason for this (but i will be honest and admit this is not my area of expertise)
meanwhile as a workaround , if you want to solo mine with AVX2, you can use hodlminer to mine against your wallet. ( This was tested by DisasterFaster )

**Comment by TheTDD** [comment]
It is not works fine on Linux and OSX either. I had to replace the assert with if condition with message and break to avoid the crashes of wallet on this assertion. I see the message appearing some times per week. I believe it is more thread sync issue on arriving of new block then the Optiminer's optimization. It makes no harm to replace assert with break here.

**Comment by ghobson2013** [comment]
I have it working on linux on e3-1240L v3 , so its not all cpu's.

**Comment by TheTDD** [comment]
I have the following CPU's available:

- Intel(R) Core(TM) i7-6950X CPU @ 3.00GHz
- Intel(R) Core(TM) i9-7980XE CPU @ 2.60GHz
- Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz
- Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz

and had this issue on all of them. I had analyzed the error and found that one side is a valid hash, but the other side if 0xffffffff...ffff. That is the signal from block.cpp that the hash is not validated or not done.

**Comment by ghobson2013** [comment]
there is a workaround for now, until I can find someone who can help with this issue.
use the hodlminer.exe against the wallet. 
https://github.com/ghobson2013/hodlminer-wolf/releases/tag/v2.4.4
Note: This was only compiled for cpu with avx2 and aes

**Comment by ghobson2013** [comment]
closing this issue, as we do not have the skills to solve it.
