### ISSUE TITLE
Missing coins in wallet

### ISSUE THREAD

**Issue by freeappmm** [ROIcoin/ROIcoin#13]
Hi, i have wallet 1.1.2 and my volume is different than on block explorer.
Means in Block explorer i should have more coins in my wallet...
It is abou 800 coins missing in my wallet...
How to solve this?
Is there a command like repairwallet or updatewallet? i have completely deleted everything in roicoin folder and resync. just backup and restore my wallet.dat and even my roicoin.conf.
Here my addr RHurHTaREtEefFKw6sZNU2NJGZThS7dmHZ, i have write the same at bitcointalk several days ago without any respone.

regards,
freeapp

**Comment by DisasterFaster** [comment]
What is your name at Bitcointalk? Also, please provide a link to your post at the ANN concerning these lost coins.

**Comment by freeappmm** [comment]
Hi,
freeapp...
https://bitcointalk.org/index.php?topic=2361848.msg27062469#msg27062469
and this one
https://bitcointalk.org/index.php?topic=2361848.msg27066563#msg27066563

regards,
freeapp

**Comment by DisasterFaster** [comment]
Thanks! I will be sending you a PM over at BitcoinTalk so keep an eye open for that please.
