### ISSUE TITLE
ROIcoind appears to attempt to bind to port 3377 twice.

### ISSUE THREAD

**Issue by seplite1** [ROIcoin/ROIcoin#14]
### Issue
When running ROIcoind, I initially got the message "cannot not bind to port 3377" using the linux binaries.

To fix this issue, I specified `-bind=127.0.0.1:4200` when starting up the daemon and it started successfully. However, looking at the ports that are bound using netstat, I see that port 3377 is still bound by ROIcoind. Furthermore, it appears that when I specify port 4200 using -bind, the daemon still runs on 3377 (specifying port 4200 in ROIcoin-cli results in `error: no response from server` and the same goes for when I run optiminer. 

It seems like ROIcoind is actually starting two processes, with the second one (the one that is configured by the cli arguments) being a dummy process and not actually functional. If this is intentional, I find this to be incredibly strange and wonder what the reasoning behind this would be. 

### Summary
Issue: ROIcoind starts two processes, which causes a conflict in binding to ports.
Reproduce: Run ROIcoind with no arguments to reproduce this error
Workaround: Specify another port for ROIcoind to bind to on startup, and connect to ROIcoind normally through port 3377

**Comment by ghobson2013** [comment]
Hi , 
Can you show us your full ROIcoin.conf file. ( you can censor out privacy info like passwords etc.. )

**Comment by ghobson2013** [comment]
add the following to your ~/.ROIcoin/ROIcoin.conf file to make it listen on your port
rpcport=4200
port=4200

**Comment by ghobson2013** [comment]
Hi seplite, 
Have you tried my suggestion yet ?

**Comment by seplite1** [comment]
Hi ghobson,
Sorry for my late response time, I had some issues come up irl.

Your suggestion created a conflict when binding to port 4200, but as long as I keep the two ports separate everything is good.

I believe this is now a duplicate of #19, which has been resolved in 1.1.4. Therefore I think it is safe to say that this issue can be closed.

Thanks for the help!

**Comment by seplite1** [comment]
close #14
