### ISSUE TITLE
Suggestion for next wallet

### ISSUE THREAD

**Issue by Bossteck** [ROIcoin/ROIcoin#2]
Hi, 

Just a small suggestion, the ROIcoins Term Deposit box currently on the Overview should be on its own tab, I currently have 19 deposits and its a bit awkward scrolling through them in the little box. Also I don't thing the sort order is working properly.

**Comment by ghobson2013** [comment]
Hi there, thanks for your proposal, sorting is alphabetical and limited by what QT4 widget library provides. most ppl sort it based on maturation block column.

**Comment by Qertuoise** [comment]
How about setup an AUTO term deposit for all incoming ROI Coins for a certain wallet address for a personal conditions?

For example. I have 2 addresses in my ROI wallet:
1 and 2. 1 is Used to mining, 2 is used to term Deposits. Its about go to the settings and make AUTO term "ON" or "OFF" with some conditions - TERM DEPOST XXX coins from address 1 for YYY days/weeks/months/years to address 2 when address 1 have the required quantity (for example XXX).

So I can have a plan. When I recieve 100 ROI on my mining address (1) from pool/solo, the wallet automaticaly (if this setting is turned ON) making a term deposit to my deposit address (2) if my wallet is running, so I dont have to do it manualy all the time and forget to deposit the coins.

**Comment by ghobson2013** [comment]
sorting has been resolved. , i will see if we can add deposittable as a new tab too.

**Comment by ghobson2013** [comment]
Qertuoise , i have added a new rpc call to create a term deposit , so what you are suggesting is scriptable now. ( listtransactions and listsinceblock already existed )

**Comment by ghobson2013** [comment]
closing this issue, as most of the suggestions have been implemented.
term deposits in its own tab idea has been rejected. There are enough sorting capabilities to arrange it the way you want and you can query the list via rpc to see in other tools like excel.
