### ISSUE TITLE
invalid transaction in wallet after crash

### ISSUE THREAD

**Issue by Ahenricks** [ROIcoin/ROIcoin#20]
The total keeps going down over time. I was mining through my wallet and later in the pool. Doesn't seem to affect it. Every New block when found is a deduction.

![support1](https://user-images.githubusercontent.com/24308550/34646999-113489f4-f33c-11e7-9a65-b7912d517377.JPG)
![support2](https://user-images.githubusercontent.com/24308550/34647000-11454a82-f33c-11e7-9231-8f11a1d74362.JPG)
![support3](https://user-images.githubusercontent.com/24308550/34647001-115374ea-f33c-11e7-9cc4-e83a16255815.JPG)
![support4](https://user-images.githubusercontent.com/24308550/34647002-11622c10-f33c-11e7-8c96-e4889093b210.JPG)

  ![support5](https://user-images.githubusercontent.com/24308550/34647365-946f7d42-f346-11e7-8bd3-5536c31bb861.JPG)
 
![capture6](https://user-images.githubusercontent.com/24308550/34647364-945c305c-f346-11e7-8941-7f04347438d0.JPG)

![support 7](https://user-images.githubusercontent.com/24308550/34647373-c25014b0-f346-11e7-9dfb-1068f3f78202.JPG)
![supprt8](https://user-images.githubusercontent.com/24308550/34647397-6128a020-f347-11e7-9a52-4e4d6155f428.JPG)

  
![support9](https://user-images.githubusercontent.com/24308550/34647415-d8904960-f347-11e7-8a34-86ecf1103e08.JPG)

![support10](https://user-images.githubusercontent.com/24308550/34647437-6c02f6ca-f348-11e7-87a4-cd82e0836a5c.JPG)
  
![sup11](https://user-images.githubusercontent.com/24308550/34653243-fe1f158c-f3ae-11e7-8cc2-6b863693e1fa.JPG)
![sup12](https://user-images.githubusercontent.com/24308550/34653244-fe405512-f3ae-11e7-9013-ab28a3661208.JPG)
![sup13](https://user-images.githubusercontent.com/24308550/34653245-fe5901c0-f3ae-11e7-8b1e-6fd278071d85.JPG)
![sup14](https://user-images.githubusercontent.com/24308550/34653246-fe686f34-f3ae-11e7-9399-7f016d717e17.JPG)
--------------
![sup16](https://user-images.githubusercontent.com/24308550/34653248-0599f84a-f3af-11e7-83a0-d765026f1052.JPG)
![sup17](https://user-images.githubusercontent.com/24308550/34653249-05ab446a-f3af-11e7-9505-6236cd67e58f.JPG)
![sup18](https://user-images.githubusercontent.com/24308550/34653250-05ba03ce-f3af-11e7-8aba-45cad56cf285.JPG)
![sup19](https://user-images.githubusercontent.com/24308550/34653251-05cce25a-f3af-11e7-8a72-55bd8d91bf1b.JPG)

--------
![sup15](https://user-images.githubusercontent.com/24308550/34653253-0db1611c-f3af-11e7-84e8-827049826b45.JPG)
![sup20](https://user-images.githubusercontent.com/24308550/34653254-0dc1732c-f3af-11e7-8437-4c087b0b30c0.JPG)

![sup21](https://user-images.githubusercontent.com/24308550/34653513-4da28ece-f3b2-11e7-863d-27a72b3adfe1.JPG)
![sup22](https://user-images.githubusercontent.com/24308550/34653547-e30bf950-f3b2-11e7-8669-3d1aceaca135.JPG)

**Comment by ghobson2013** [comment]
Hi can you post another snapshot once you see new values so i can compare.
Also which wallet version are you using ?

**Comment by Ahenricks** [comment]
wallet 1.1.2

.56497023
.56340262

**Comment by ghobson2013** [comment]
i understand your balance is going down but i need to see the subbalances on the termdeposit table between 2 snapshots to identify exactly which ones are going down.  The totals dont help me.

I also will need you to go to settings and enable coin control , then open coincontrol via send or deposit window ( input button )  and make 2 screenshots so i can see which ones are going down in value.

thanks for your cooperation.

**Comment by ghobson2013** [comment]
please provide me with the following info:
Your wallet address
The response of doing the following command in the debug console window:    getblockhash 32685

**Comment by Ahenricks** [comment]
Sorry, how do I find my wallet address? Or do you mean a recieving address? 
13:17:59 (getblockhash 32685)
￼
0000000de25dc81231f2e90d7bf2fe00f20db2eaf34e4d0b2178655148de2ba0

Also went ahead and uploaded addition requested screenshots.
Thanks

**Comment by Ahenricks** [comment]
From my observations, it looks like Deposit #18 is the one going down in value.
Edit: This might have been the deposit of when my wallet crashed when doing the transaction. 
Edit 2: I think this was the deposit that failed which is number 18. Hopefully, this has narrowed down the possibilities. Screenshot above.
Edit 3: Hold on. Looks like the deposit number is not staying the same. It's staying 1 ahead of the actual block number. Screenshot to prove above.
  thanks

**Comment by ghobson2013** [comment]
please try the following:
1- backup your wallet.dat file
2- start the wallet with the following flags:   -rescan -zapwallettxes=2
wait till you see in the debug.log "rescan    29333ms"  , then check the values again.

**Comment by Ahenricks** [comment]
Went ahead and did that. It completely removes that transaction and my total goes down to 6390 ish. Should have 6500. Am i just SOL? Forget those 20 coins i suppose?
thanks for your help

**Comment by ghobson2013** [comment]
Hi you had a corrupt transaction in your wallet.dat, the zapwallet flag basically tells the wallet to rescan your balance based on what is actually on the blockchain. So that specific bug is now resolved.
 Can you tell us your wallet receive address ,i ll send you some coins.

**Comment by Ahenricks** [comment]
Thanks for the work you put in. Glad the rescan took care of it. Hopefully, if anyone else is having this issue we can refer to the rescan to solve the issue
Much thanks again

Receiving Address
RUnDTicfher8NhJchBLAq6r9nNMFPtrdnA

**Comment by ghobson2013** [comment]
That address doesn't exist according to the block explorer, can you make a new receive address and provided it to me ( it will still be associated with your wallet ).

**Comment by Ahenricks** [comment]
I generated another one: RUHEr5HfoBbZdzHJTwNbJ6RSdb7rNQf9m4

**Comment by ghobson2013** [comment]
coins sent thanks for your patience
