### ISSUE TITLE
Question about cpu performance for solo mining the HODL algorithm.

### ISSUE THREAD

**Issue by dreamz33** [ROIcoin/ROIcoin#21]
I am mining with "solo mining on“ option in wallet app.

I am using x5650 cpu,which based on westmere-ep architechture.It supports the following instructions:x86, x86-64, MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, AES
I want to upgrade cpu for mining.What kind of cpu can achieve best performance?

intel avx? intel avx2? intel avx-512? amd ryzen?

**Comment by ghobson2013** [comment]
Hi there, 

You can find performance information for the HODL algorithm here
http://hodlcoin.oo.fi:8080/cpus/CPU_vs_Hash_rate.xhtml

I don't personally tell people what hardware to buy, as it depends on many factors, your budget, the cost of electricity , your preference for intel vs AMD, etc...

Hope this helps.

**Comment by dreamz33** [comment]
hi ghobson2013,
Thank you!I have checked your link,and found out that new cpu architecture has little improvement  on HODL mining(i.e. ryzen 1800x OC only 2.3 times faster than W3690(westmere-ep,a 2010 year architecture). 
Is this because HODL doesn't use newest cpu instruction set such as AVX256 and AVX2?
Your link indicates HODL mining performance.Do you know ROI-coin wallet program solo mining performance?
Thank you!

**Comment by ghobson2013** [comment]
ROI uses HODL algorithm so its the same.
HODL algorithm uses AES searches, so avx2 does give a boost, as shown by users on bitcointalk.
usually between 20-100% improvement, i don't know about AVX256 sorry.
you can test avx2 with https://github.com/ghobson2013/hodlminer-wolf/releases/tag/v2.4.5

**Comment by dreamz33** [comment]
Ok.Thank you!
