### ISSUE TITLE
QT: On Deposit Tab, the list of addresses should include own addresses

### ISSUE THREAD

**Issue by TheTDD** [ROIcoin/ROIcoin#22]
The addresses from "Receiving addresses" should be shown in the Address-Chooser Popup window which opens by pushing "Choose previous used address". Because the Deposits should be created with own address as target, this feature will simplify the creation of deposits by easy selection of address.

**Comment by ghobson2013** [comment]
https://github.com/ROIcoin/ROIcoin/releases/tag/v1.1.4.000 has been released, closing this bug.
