### ISSUE TITLE
Miner not working after change CPU

### ISSUE THREAD

**Issue by dreamz33** [ROIcoin/ROIcoin#28]
I have worked about 260h/s with my X5650@4.5G,and received approximately 120 ROI  everyday,with mining option on in windows QT wallet.But not a single ext-miner program(different versions of hodlminer)got me any ROI,though everything seems right.
Now I upgraded to e5 2680v2@3.1G.Windows QT wallet crushes every time when I turn mining option on.Ext-miner program seems working,but I can not get any ROI outcome.

Why is this happening?

Actually I checked the address several times,I am sure it is correct.
This is my configuration:

roicon.conf:

rpcuser=mylocal

rpcpassword=djfasd

rpcallowip=0.0.0.0/0

rpcport=25111

rpcthreads=18

server=1

daemon=1

gen=0

miningaddress=RGASNmjKJ8xpbZ4VLUYBBTQewRT9oG1kLu

addnode=128.199.252.224

hodlminer command line:

hodlminer.exe -o http://127.0.0.1:25111 -u mylocal -p djfasd -t 18 -q -D  --coinbase-addr=RGASNmjKJ8xpbZ4VLUYBBTQewRT9oG1kLu

(-t 18 is because that if I use full 20 threads,hodminer will crash on start,only <=18 threads works fine.My cpu is e5 2680 v2,which is 10 cores 20 threads)

Also,I have encountered the following problem:When I use older x5650@4.5g cpu,the wallet inner miner works fine,ext hodlminer works when pool mining,but no outcome when solo mining;but when I use newer e5 2680v2 cpu,the wallet inner miner crashes,ext  hodlminer no outcome when solo mining.I am sure hodlminer is successfully connected to wallet and working seems fine.
This is a typical debug message section:

"deleted due to too many words"

**Comment by ghobson2013** [comment]
Hi, 

Can you add to ROIcoin.conf the following parameter
debug=
(without a value it means all debug)
optimineraes=1
optimineravx2=0   
( your new chip doesn't support AVX2 )

and then run on windows and try the miner so we can see more details.
Provide me the debug.log so i can check ( don't paste the content in github please, attach it ).

thanks, 
//Gary

**Comment by dreamz33** [comment]
hi ghoboson2013,
I tried add optimineraes=1,optimineravx2=0, wallet immediately crashed when I turn on "solo mining on"option.In fact,every time I put optimineraes=1 option in bat command line,the wallet crashes immediately on mining;if I don't put anything in bat command line,the wallet crashes after start mining for 1 second.
After I put "debug=" line in roincoin.conf ,the debug.log shows as following(complete message,from start wallet to crash:
[debug.crash.log](https://github.com/ROIcoin/ROIcoin/files/1643324/debug.crash.log)

**Comment by ghobson2013** [comment]
not sure why optimineraes would not work for your CPU, but we have seen this before.
ok lets leave it off for now.

Try reducing the number of cores first and see if its stable.
Example add to ROIcoin.conf
genproclimit=8
minermemory=2

minermemory will tell the 8 cores to spread over 2 batches of memory each consuming 1Gb of RAM.
I suspect doing 18 threads ( which are only 10 physical core ) all working on the same 1Gb of RAM might cause an issue.

so 2 variables control this, genproclimit tells the wallet how many cores to use and 
minermemory tells the wallet how many groups to subdivide the cores in... 

so start slow...
genproclimit=1
minermemory=1 

if this works , keep increasing genproclimit until it crashes , if it does double the minermemory and see if it has an effect.

Warning: DO not paste logs in a github issue window, drag and drop your file in the window instead !!

**Comment by dreamz33** [comment]
Thank you! I am trying now.
By the way ,do you mean genproclimit= indicates physical cores,such as my 10 cores;and minermemory= indicates divide physical core into how many threads,such as 2 threads each core?

**Comment by ghobson2013** [comment]
yes so example 
genproclimit=8
minermemory=2
means 2 GB of RAM will be used and 4 cores will work on 1GB of ram and the other 4 cores will work on another 1GB of RAM in parallel.

**Comment by dreamz33** [comment]
hi,after I made these changes,still crashes:
optimineraes=0
optimineravx2=0
genproclimit=1
minermemory=1

**Comment by dreamz33** [comment]
[debug.crash.log](https://github.com/ROIcoin/ROIcoin/files/1643489/debug.crash.log)

**Comment by dreamz33** [comment]
genprolimit= indicates physical cores or logical threads?My cpu is 10 cores 20 threads(Hyper-threads tech),genprolimit should be 10 or 20?

**Comment by ghobson2013** [comment]
I don't see any information about the crash in the log, is there an error on the screen or in the windows event log , in Event Viewer->Windows Logs->Application log ?

**Comment by dreamz33** [comment]
This is Event Viewer->Windows Logs->Application log:
Error application name: ROIcoin-qt_x64_v1130.exe，version: 1.1.3.0，time stamp: 0x5a44f980
Erro module name: ROIcoin-qt_x64_v1130.exe，version: 1.1.3.0，time stamp: 0x5a44f980
Error code: 0xc0000005
Error offset: 0x0000000000200c8b
Error process ID: 0x4f7c
Error application start time: 0x01d3907730093e38
Error application path: D:\挖矿\roicoin\ROIcoin-qt_x64_v1130.exe
Error module path: D:\挖矿\roicoin\ROIcoin-qt_x64_v1130.exe
Report ID: 123fd6d4-acbc-4262-ad75-516de2b43111
Error program full name:

**Comment by dreamz33** [comment]
Error bucket 1770632677472263310，type 4
Event name: APPCRASH
Response: N/A
Cab Id: 0

Problem signature:
P1: ROIcoin-qt_x64_v1130.exe
P2: 1.1.3.0
P3: 5a44f980
P4: ROIcoin-qt_x64_v1130.exe
P5: 1.1.3.0
P6: 5a44f980
P7: c0000005
P8: 0000000000200c8b
P9: 
P10: 

Attach files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER445A.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4546.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4554.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4574.tmp.txt

Where to find these files:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_ROIcoin-qt_x64_v_a390578c958370732f772a114beea37458bc52_62405f0b_613e6afd

Analysis symbol: 
Recheck solution: 0
Report Id: 123fd6d4-acbc-4262-ad75-516de2b43111
Report status: 268435456
Hash bucket: b02b8babf81b649098928d09f86edc8e

**Comment by ghobson2013** [comment]
Thanks i am not sure what is causing this, error 0xc0000005 is a general error that can mean many things from access violation to bad memory.  Can you provide the files in C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_ROIcoin-qt_x64_v_a390578c958370732f772a114beea37458bc52_62405f0b_613e6afd directory ?
I will see if i can find more clues..

**Comment by dreamz33** [comment]
[Report.wer.txt](https://github.com/ROIcoin/ROIcoin/files/1643613/Report.wer.txt)

**Comment by dreamz33** [comment]
This is the only file I found in that directory.

**Comment by ghobson2013** [comment]
In the mean time please try v1.1.2   ( v1.1.3 only had some lowlevel rpc calls added for sysadmins ).

**Comment by dreamz33** [comment]
v1.1.2 has the very exact crash.

**Comment by ghobson2013** [comment]
it may also be useful to run sfc /scannow , just to check all system dll's are fine.

**Comment by dreamz33** [comment]
Scaning now.
But should be fine.
When I use older X5650 cpu,wallet mining runs just fine for days.
As soon as I change to this newer E5 2680 V2 cpu,wallet crashes everytime when mining.
The only difference between two cpus is the newer one has AVX support.

**Comment by dreamz33** [comment]
some hodlminer.exe working fine,but hashrate is slow ,looks like no AVX support;other hodlminer.exe crashes using 20 threads by default,but working fine put -t 18 to restrict 18 threads,and hashrate doubles,looks like AVX has been activated.

**Comment by dreamz33** [comment]
The former one,hashrate is 333 h/s;the later one,hashrate is 660 h/s.Though they are complied by different people.

**Comment by ghobson2013** [comment]
understood. thanks for the info.

**Comment by dreamz33** [comment]
What should I do now?Though they both working seems fine,they can't provide any ROI outcome.
In fact,the only way to mine ROI is using older X5650 cpu and in wallet miner,or ext miner to mining at pool.Any other way failed.

**Comment by ghobson2013** [comment]
I am confused you said you had a hodlminer working with -t18 with avx , isnt that providing you ROI income ?  you can point hodlminer at your wallet , this will work and does not need the wallet miner.

**Comment by dreamz33** [comment]
I did what you said.But I can't get any ROI income by this way,even when I use older X5650 cpu. Ironically,I can get ROI income when using ext miner on pool,though income is only 1/3 comparing to wallet miner.

**Comment by ghobson2013** [comment]
finding new blocks depends on the global hash rate and the dificulty level, did you expect to find 1 block a day with just 300-600H/s ?

**Comment by dreamz33** [comment]
Actually I did find 1 block a day with just 260h/s(X5650 cpu),from 2017/12/30 to 2018/1/9.
After 2018/1/10, I changed to e5 2680 v2 cpu,till now I get absolutely zero ROI income.

**Comment by dreamz33** [comment]
Last night I went back to my X5650 cpu using in wallet miner,after an hour of mining@260h/s,I got my first 120 ROI in 10 days...

**Comment by ghobson2013** [comment]
Congratulation.

The following is true for all altcoins:

Your profit relates to the amount of hashing power you contribute to the network. Since your mining power is constant, your share of the total hashing power decreases relatively when the network's hashing power increases. I.e. we can deduce the following formula:

newProfit = currentProfit * currentDiff/newDiff

I am going to close this issue now.
Have a good weekend.
