### ISSUE TITLE
High CPU usage when fully synced and not mining on 32 bit OS

### ISSUE THREAD

**Issue by jsveto** [ROIcoin/ROIcoin#31]
Wallet compiled on Linux with configuration flags --with-gui=no --enabled-tests=no

When fully synced ROIcoind uses aprox. 50%-80% of CPU core. Is this normal?

**Comment by ghobson2013** [comment]
What OS did you build on , and what exact build steps did you follow ?

**Comment by jsveto** [comment]
OS: kubuntu 16LTS

./autogen.sh
./configure --with-gui=no --enable-tests=no
make
sudo make install

**Comment by ghobson2013** [comment]
ok i will test it out and let you know.

**Comment by ghobson2013** [comment]
Keep in mind that roicoind still functions as a p2p node even if you don't mine. It will serve out blocks to clients who are syncing , it will relay transactions , etc.. this will cost cpu. if you  run with debug , you ll be able to see if your receiving/sending blocks/transactions etc..

**Comment by jsveto** [comment]
i understand that, but it still seems unreasonably high. i Have checked debug.log file,
i am getting a lot of following debug msgs (About 600 per second):

.....
2018-01-20 21:14:41 keypool return 13
2018-01-20 21:14:41 keypool reserve 13
2018-01-20 21:14:41 keypool return 13
2018-01-20 21:14:41 keypool reserve 13
2018-01-20 21:14:41 keypool return 13
2018-01-20 21:14:41 keypool reserve 13
.....

**Comment by ghobson2013** [comment]
i am running now fully synced on 16.04 and only see 0.3% cpu , so something else is going on.
ok add to ROIcoin.conf debug= ( without a value means all events ). restart till your at the same issue then send me the entire log + your ROIcoin.conf so i can verify...

**Comment by ghobson2013** [comment]
It would be easier if you joined our discord or slack channel ...

**Comment by ghobson2013** [comment]
We do not support 32 bit OS anymore. Many major vendors like nvidia are dropping support for it.

**Comment by jsveto** [comment]
I installed 64bit Linux. CPU usage is much lower and it averages just above 10% on Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz

Thanks

**Comment by ghobson2013** [comment]
Glad to hear it, i should have asked first if it was 64 bit. closing this issue.
