### ISSUE TITLE
Problem with coins after updating to version 1.1.3

### ISSUE THREAD

**Issue by daltonbezerra** [ROIcoin/ROIcoin#33]
So, this morning I did the update to the version 1.1.3, (I was on version 1.1.2), and I followed all the instructions just like the PDF file told to do. Everything went great, and my wallet block number matches the block explorer, (I did not check before the update if it was matching or not). 

There is only one problem, after the syncing I noticed that the coins that I minerated last night disapeared, (they were still pending confirmation when I did the update). I did backup my wallet before AND after updating it, so I was wondering if there is a way to recover those coins?

**Comment by DisasterFaster** [comment]
How many coins did you lose Dalton? Can you please submit a copy of your debug.log (located in your ROI coin data directory) so the dev team can check into this issue for you?

**Comment by daltonbezerra** [comment]
I lost 480 coins, here is a copy of the debug.log as requested.

[debug.log](https://github.com/ROIcoin/ROIcoin/files/1679691/debug.log)

**Comment by DisasterFaster** [comment]
Based on a review of your debug log it shows no found blocks.
