### ISSUE TITLE
Lost coins after updating to hotfix

### ISSUE THREAD

**Issue by Teknickgit** [ROIcoin/ROIcoin#34]
Hi, Lost about 4000 coins when I updated. I have attached the debug log for you to see.

Thanks for any help.

[debug.zip](https://github.com/ROIcoin/ROIcoin/files/1680283/debug.zip)

**Comment by DisasterFaster** [comment]
The block reward is 120 coins so 4000 coins would not be a total amount representing a quantity of 120 coin blocks. A review of your submitted log shows that there were 2 mined blocks which would be a total of 240 coins and the details are below:

2018-01-30 08:10:24 ROIcoinMiner: proof-of-work found  
2018-01-30 13:10:17 ROIcoinMiner: proof-of-work found

If you could please supply a good ROI coin wallet address from a wallet that is the most recent version and also fully synchronized and matching our official block explorer... I will send you 240 replacement coins.

**Comment by Teknickgit** [comment]
Sure,

But I remember seeing over 8000 coins on that machine and when I updated it
was 4000 odd less. I don't recall the exact numbers.

Inwish I had taken screenshots so you could see.

Would the wallet. DAT files help? I guess it was on the wrong chain because
it was turning he coins around very fast.

Nick


On 31 Jan 2018 11:24 PM, "DisasterFaster" <notifications@github.com> wrote:

The block reward is 120 coins so 4000 coins would not be a total amount
representing a quantity of 120 coin blocks. A review of your submitted log
shows that there were 2 mined blocks which would be a total of 240 coins
and the details are below:

2018-01-30 08:10:24 ROIcoinMiner: proof-of-work found
2018-01-30 13:10:17 ROIcoinMiner: proof-of-work found

If you could please supply a good ROI coin wallet address from a wallet
that is the most recent version and also fully synchronized and matching
our official block explorer... I will send you 240 replacement coins.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ROIcoin/ROIcoin/issues/34#issuecomment-361965673>, or mute
the thread

**Comment by Teknickgit** [comment]
Hi,

Sorry for the delay - the address is RHKatB47HNKLHF9nsyYfT3rMDZTWozCFQz

On another note I am really interested in hosting a pool on our server - I
am running UBUNTU server 14.04. Do you have a set of instructions for
getting it up and running? I am already running a Dash p2pool (
http://210.3.80.58:7903/static/) and I would like to try and help this
project if I can.

Nick
