### ISSUE TITLE
Lost coins after update to hotfix 

### ISSUE THREAD

**Issue by TurdSmurf** [ROIcoin/ROIcoin#35]
pretty much same as post below I followed all instructions in pdf everything looked fine blocks match but my coins are all gone 
[debug.log](https://github.com/ROIcoin/ROIcoin/files/1682201/debug.log)

**Comment by DisasterFaster** [comment]
Your debug log begins on 2018-01-31 15:13:12 which is well past the fork so I won't be able to do anything with analyzing and/or replacing your lost coins.
