### ISSUE TITLE
Errors after fork (hotfix applied)

### ISSUE THREAD

**Issue by Afterdark37** [ROIcoin/ROIcoin#36]
Since the fork I have been getting a lot of these errors, and the amount of blocks found seems to have dropped considerably (i may just be getting unlucky).  I did the hotfix repair and am in sync with the block explorer.  I also never received the 6 or so blocks found around the time of the fork, i'm not sure if any of this is normal.

2018-01-31 14:36:06 socket recv error An existing connection was forcibly closed by the remote host.  (10054)
2018-01-31 10:47:38 ERROR: AcceptToMemoryPool: free transaction rejected by rate limiter

Also, on opening of the application and starting mining I get the following:
2018-01-31 14:49:16 CDBEnv::Open: LogDir=C:\Users\Michael\Desktop\ROI\database ErrorFile=C:\Users\Michael\Desktop\ROI\db.log
2018-01-31 14:51:45 ERROR: Read: Failed to open file C:\Users\Michael\Desktop\ROI\banlist.dat

Is this normal?  Any advice?  I am new to crypto and mining.  Thanks!
[debug.log](https://github.com/ROIcoin/ROIcoin/files/1682728/debug.log)

**Comment by ghobson2013** [comment]
Hi Afterdark, 

The socket recv error just means you were connected via p2p to a peer node and it decided to stop abruptly ( like someone just pressing the X on the top right corner of his wallet window ). This is normal behavior.

The second error means someone is producing a lot of transactions in a short amount of time, example a pool paying out to hundreds of ppl in one go. The wallet has a built-in rate limiter to prevent spamming the mempool, this is normal behavior. Those transaction will be retried and added to another block.

finding blocks depends on luck but also on your hashrate / global network hashrate % ratio.
The debug log you found only shows 1 found block.
2018-01-31 17:46:28 ROIcoinMiner: proof-of-work found

**Comment by Afterdark37** [comment]
So all normal then, thanks!
