### ISSUE TITLE
Wallet crashing when mining.

### ISSUE THREAD

**Issue by Afterdark37** [ROIcoin/ROIcoin#38]
Hello, my wallet keeps crashing while mining overnight.  Last entry in the debug log is:

2018-02-08 05:26:20 ROIcoinMiner: Hashes Per Second=430 (total seconds=62 hashes=26679)
2018-02-08 05:26:20 Optiminer Flags: AES-NI = 1, AVX2 = 0
2018-02-08 05:26:20 Optiminer Flags and CPU support: AES-NI = 1, AVX2 = 0
2018-02-08 05:26:21 create sha512 data 1.078
2018-02-08 13:08:25 GUI: "registerShutdownBlockReason: Successfully registered: ROIcoin Core didn't yet exit safely..."
2018-02-08 13:08:25 

This happens after mining for a few hours, and started appearing after the hotfix.  Also, this may or may not be related, but I no longer successfully mine blocks solo with 400-550h/s since the hotfix.  Before the hotfix it was 2-4 blocks a night.

[debug.log](https://github.com/ROIcoin/ROIcoin/files/1707112/debug.log)

**Comment by ghobson2013** [comment]
Hi Afterdark,

**Comment by ghobson2013** [comment]
The hotfix only changed a single line in main.cpp around blockreward variance, I doubt its causing your issue. What cpu brand/model is it ? Please check the windows event log see if it has more info about the crash. As a workaround i suggest your use hodlminer and point it at your wallet instead of the built-in miner.

**Comment by Afterdark37** [comment]
i7 7700k.  There is nothing in the windows event log, the error message I get comes from the wallet.  I'm new to mining, how do i use my hodlminer with the wallet?  What address?  

Thanks.

**Comment by ghobson2013** [comment]
You need to edit your ROIcoin.conf. Locate and if needed create ROIcoin.conf
(default location C:\Users\username\AppData\Roaming\ROIcoin\ short cut %appdata%\ROIcoin\) and add lines:
	server=1
	rpcuser=<rpc_user_name>
	rpcpassword=<random_rpc_password>
	rpcport=3376
	rpcthreads=8
Choose your username and a strong passowrd. Set atleast two RPC threads per miner by using parameter 'rpcthreads'.

Start your wallet (ROIcoin-qt) and start hodlminer:
hodlminer.exe -o http://127.0.0.1:3376/ -u <rpc_user_name> -p <random_rpc_password> -D --coinbase-addr=<your_public_wallet_address> ( usually one of your receive keys )

By default wallet and ROIcoind accept connections from local host only. You can add allowed IPs by using parameter 'rpcallowip'.
	rpcallowip=<ip>
Rpcallowip allow JSON-RPC connections from specified source. Valid for <ip> are a single IP (e.g. 1.2.3.4), a network/netmask (e.g. 1.2.3.4/255.255.255.0)
or a network/CIDR (e.g. 1.2.3.4/24). If your local LAN uses eg. adresses
192.168.1.xxx, 192.168.1.0/24 will allow connections from all clients in your local LAN.

**Comment by ghobson2013** [comment]
you can find hodlminer.exe here https://github.com/Orava2/hodlminer-binary
