### ISSUE TITLE
QT: Tab Overview, Deposits Table Column Sorting is alphanumeric

### ISSUE THREAD

**Issue by TheTDD** [ROIcoin/ROIcoin#39]
By changing sorting order in numerical fields such as "Principal", "Interest", "Value", "On maturation" and "Term" the sorting happens in alphabetical order. The content of fields is compared as string. It should be compared as numbers to get correct sorting.

**Comment by ghobson2013** [comment]
unfortunately QTable is pretty limited in terms of sorting types,
Qt.SortOrder = The items are sorted ascending e.g. starts with 'AAA' ends with 'ZZZ' in Latin-1 locales
As documented here
http://doc.qt.io/qt-4.8/qtableview.html#sortByColumn
http://doc.qt.io/qt-4.8/qt.html#SortOrder-enum

i am open to suggestions but couldnt find an easy answer.

**Comment by TheTDD** [comment]
Custom sorting behavior is achieved by subclassing QSortFilterProxyModel and reimplementing lessThan(), which is used to compare items.

http://doc.qt.io/archives/qt-4.8/qsortfilterproxymodel.html

"Transactions" Tab uses this and sorts by "Amount ROI" correctly. Coin selections dialog sorts nice by Amount, Input, Interests and Confirmation too.

**Comment by ghobson2013** [comment]
resolved in 1.1.4 , https://github.com/ROIcoin/ROIcoin/releases/tag/v1.1.4.000 has been released, closing this bug.
