### ISSUE TITLE
Windows10 Alert Notification for matured coins

### ISSUE THREAD

**Issue by SKR4PS** [ROIcoin/ROIcoin#40]
In Windows 10, when we receive a transaction we receive a notification in Action Center. It would be nice to see it for matured coins.

**Comment by ghobson2013** [comment]
Hi, I try to avoid having to write platform specific code in the wallet , i will check it out and see if this is something simple.  Meanwhile there are 2 ways to see matured coins, in the deposit table itself their status will say matured and under the term deposit table there is a total counter that says total matured.

**Comment by TheTDD** [comment]
The notifications of ROIcoin-QT appear on OSX as native notification, so that should be not platform specific code to achieve this, rather QT provides it for every platform.

**Comment by SKR4PS** [comment]
@ghobson2013 @TheTDD Yes! The little I know it's just a messagebox that is handled differently in each OS. It would very useful to remember us to move our coins. Cheers!

**Comment by ghobson2013** [comment]
https://github.com/ROIcoin/ROIcoin/releases/tag/v1.1.4.000 has been released, closing this bug.

**Comment by SKR4PS** [comment]
@TheTDD @ghobson2013 Very nice, thanks!
