### ISSUE TITLE
Just did 1.1.3 upgrade, lost coins

### ISSUE THREAD

**Issue by dakotadouglas** [ROIcoin/ROIcoin#41]
I apparently missed the notification about the update, but just did this.  It appears that I lost some points.  Pre-upgrade I had around 4300, and post-upgrade I only have approximately 972.  I checked my debug.log file and it only contains information since the upgrade, but I have a wallet backup file.  Were my other coins due to the bug?

**Comment by DisasterFaster** [comment]
I'm so sorry to hear about this. Can you please provide a copy of your debug log so the dev team can look it over?

**Comment by dakotadouglas** [comment]
That wasn't one of the files I was replacing as part of the upgrade, so I didn't back it up, and it looks like two days ago it was replaced by the upgrade to v1.1.3.  I have a wallet backup file, so if there is a way to recreate it from that I can try, otherwise I don't have it for the time frame of the coins.

**Comment by DisasterFaster** [comment]
ok well just send whatever debug.log that you have.

**Comment by dakotadouglas** [comment]
[debug-log-20180214a.zip](https://github.com/ROIcoin/ROIcoin/files/1733406/debug-log-20180214a.zip)
