### ISSUE TITLE
QT: Wrong calculation of Estimated date of Deposits - Dates are too far in the future

### ISSUE THREAD

**Issue by TheTDD** [ROIcoin/ROIcoin#42]
There is old HODL code found in qt/overviewpage.cpp (line 240)

`rawtime += blocksRemaining*154;`

154 sec. is the block time of HODLcoin. ROIcoin uses 120 sec, therefore the code should be written as

`rawtime += blocksRemaining*120;`

**Comment by ghobson2013** [comment]
https://github.com/ROIcoin/ROIcoin/releases/tag/v1.1.4.000 has been released, closing this bug.
