### ISSUE TITLE
Can't set ban on arbitrary time - parameter parsing issue

### ISSUE THREAD

**Issue by TheTDD** [ROIcoin/ROIcoin#44]
I want to ban the nodes on wrong chain for longer then one day, but it is not possible.

This works and bans for 24 hours:

```
./client setban 118.45.134.66 add
```

This doesn't work:

```
./client setban 118.45.134.66 add 604800
error: {"code":-1,"message":"value is type str, expected int"}

./client setban 73.168.84.118 add 604800
error: {"code":-1,"message":"value is type str, expected int"}
```

**Comment by ghobson2013** [comment]
i will fix it, i think i see the problem, i need to add it to rpcclient conversion table
meanwhile you can control the default 24hr using the bantime parameter at startup.

**Comment by ghobson2013** [comment]
https://github.com/ROIcoin/ROIcoin/releases/tag/v1.1.4.000 has been released, closing this bug.
