### ISSUE TITLE
QT: find way to freeze deposit table updates during initial blockchain sync

### ISSUE THREAD

**Issue by ghobson2013** [ROIcoin/ROIcoin#47]
Currently the UI is updating the term deposit table during a block chain sync on every block.
The more deposits you have the more expensive this operation becomes.
Find a way to freeze update until after the chain is fully synced.

**Comment by TheTDD** [comment]
I'll try to solve this with the delayed processing of deposit data once in 5 seconds.
I'll use the QThread, signals and slots.

In sync time when the blocks are coming fast the deposit table will be not refreshed. The deposit table will be refreshed in 5 seconds after last block arrived. After sync is done, every new refresh of deposit table will happen after 5 seconds of next block.

**Comment by ghobson2013** [comment]
https://github.com/ROIcoin/ROIcoin/releases/tag/v1.1.4.000 has been released, closing this bug.
