### ISSUE TITLE
Update issue: Coins immature

### ISSUE THREAD

**Issue by activecarbon** [ROIcoin/ROIcoin#50]
Just updated wallet to 1.1.4 and now have over 17,000 coins displayed as immature when using getwalletinfo command in console:
{
"walletversion" : 60000,
"balance" : 1001.56770472,
"unconfirmed_balance" : 0.00000000,
"immature_balance" : 17074.54109323,
"txcount" : 182,
"keypoololdest" : 1517883555,
"keypoolsize" : 100,
"unlocked_until" : 0
}
The block number matches the explorer and the debug file is too large upload (40MB)

**Comment by activecarbon** [comment]
Got the debug file compressed enough
[debug.zip](https://github.com/ROIcoin/ROIcoin/files/1750434/debug.zip)

**Comment by ghobson2013** [comment]
immature_balance is the amount of coins you will receive when all your term deposits mature.
What exactly is the issue ?

**Comment by activecarbon** [comment]
sorry, my misunderstanding, my immature_balance was around the same as my available balance proir to update. now i only have 1001.56770472 available balance and not  the 18,000+ coins  available i had pior to update. also one of my term deposits says its "deposit block" is always one block ahead of explorers' block, and no interest is being applied to it.

**Comment by ghobson2013** [comment]
It looks like you resync'd after the upgrade, you probably have transactions that need to be zapped from when you were on the wrong chain, shutdown your wallet , backup your wallet.dat  , then restart with the following flags -rescan -zapwallettxes=2  , let me know if that resolves it.

**Comment by activecarbon** [comment]
applied flags, -rescan -zapwallettxes=2, and lost both of my term deposits and my balance is still only just over 1000, so now i'm missing 30,000+ all up not just 17000

**Comment by ghobson2013** [comment]
Those were coins you mined on the wrong chain.
