### ISSUE TITLE
ROI app version 1.1.4

### ISSUE THREAD

**Issue by daltonbezerra** [ROIcoin/ROIcoin#51]
Just a little heads up I've encountered so far. First time I executed the app, Windows SmartScreen blocked it.
I've executed it anyway, but some people might feel a little uncomfortable doing it. Thought You should know. :)

**Comment by ghobson2013** [comment]
Thanks, I don't sign the windows binaries, that is a complicated and expensive rabithole a lot of opensource projects struggle with. I cross compile all the wallets from ubuntu, so anything that requires special tools on windows is not going to work. Fortunately there are online examples of how to bypass this Microsoft feature, the provided signatures should be enough to check if you downloaded the right binaries.

Examples: https://github.com/mintty/wsltty/issues/32 and https://security.stackexchange.com/questions/139347/smart-screen-filter-still-complains-despite-i-signed-the-executable-why

**Comment by ghobson2013** [comment]
closing this issue as i don't intend on signing windows binaries.
