### ISSUE TITLE
mining is ongoing but can not be seen the coins from wallet

### ISSUE THREAD

**Issue by rpzxjp** [ROIcoin/ROIcoin#54]
My receive address is RGASW97dZarEFGsMBzMZ7BX1dBM7iRvx5m, I can see my mining progress from the mining pool address of http://roi.optiminer.pl:8081, but from this morning , I can not see the income of ROI coins on my wallet, even though I updated the latest wallet version.

**Comment by ghobson2013** [comment]
Does your wallet v1.1.6 block height match the block explorer ?

**Comment by rpzxjp** [comment]
How to see block height and bock explore?

**Comment by ghobson2013** [comment]
https://roi-coin-blockexplorer.roi-coin.com/
69647 right now

**Comment by rpzxjp** [comment]
I still can not understand how to solve my wallet problem?

**Comment by ghobson2013** [comment]
Your wallet needs to be on the correct chain. This is why i am asking if your wallet block height is the same as the last block on the block-explorer. When you go to Help->Debug window , what block nr do you see on the screen ?

**Comment by rpzxjp** [comment]
The block nr of my wallet is 69485. So how to solve this problem? Thank you

**Comment by ghobson2013** [comment]
Ok your wallet is on the wrong chain.
I will assume you are on Windows ? 

goto %APPDATA%/ROIcoin folder , you will see there the wallet.dat file , back this file up !!
In the same folder you will see 2 subfolders called "blocks" and "chainstate" , delete them.
Download this file https://github.com/ROIcoin/ROIcoin/releases/download/v1.1.6.000/bootstrap-432018.zip
unzip it and copy it to the %APPDATA%/ROIcoin folder ( same folder where your wallet.dat is ).
Now start ROIcoin-qt.exe with the commandline option -loadblock=bootstrap-432018.dat 
This will import the correct blockchain.  
Note: the loadblock commandline option expects you to provide full path to the bootstrap file, so this depends on where you downloaded it on your local drive.

If this is too difficult for you then just delete the "blocks" and "chainstate" subfolder and restart the v1.1.6 wallet it will re-sync the blockchain over the network ( which is slower ).

**Comment by rpzxjp** [comment]
Sorry, my computer is Mac

**Comment by ghobson2013** [comment]
No problem, 
Look in the folder:
/Users/YOUR_USERNAME/Library/Application Support/ROIcoin

backup your wallet.dat , delete the blocks and chainstate subfolder
download and unzip https://github.com/ROIcoin/ROIcoin/releases/download/v1.1.6.000/bootstrap-432018.zip

Then run ROIcoin-qt -loadblock=bootstrap-432018.dat
bootstrap-432018.dat is what is inside the downloaded bootstrap zip file(edited)
loadblock flag needs full path to the bootstrap file
if this is too complicated, then you can just delete blocks and chainstate subfolder and start wallet , it will then resync from the network , which is slower than reading from the local bootstrap file.

**Comment by rpzxjp** [comment]
I deleted those two subfolder and the wallet is resuncing now. Thank you very much.

**Comment by rpzxjp** [comment]
It worked. Thank you
