### ISSUE TITLE
Can not send ROI to online market wallet.

### ISSUE THREAD

**Issue by dreamz33** [ROIcoin/ROIcoin#56]
I can not send any ROI to my wallet in cryptohub.online and coinsmarkets.com.No matter how many ROI I sent,my local gui wallet says transaction successful,but my wallet in online market is always empty.
what happened?

**Comment by dreamz33** [comment]
ps:I succesfully sent some ROI to coinsmarkets.com a month ago.But now always fail.

**Comment by ghobson2013** [comment]
Hi, 
coinsmarkets.com should not be used as it is not currently online, their ROI wallet is offline, along with most other coins for months now, you can follow the drama on https://bitcointalk.org/index.php?topic=2185903.3300

cryptohub.online should work. Are you on ROIcoin v1.1.6 ? , 
does your wallet block height match our block explorer https://blockexplorer.roi-coin.com/api/getblockcount ? 
does getblockhash 73136 show 000000792baa2570dcd24f1d0dab6e8e18e010e951dae7a06e3370d49c4cee1e ?

**Comment by dreamz33** [comment]
You are right，after resync I successfully made a transaction to cryptohub.
THank you!
