### ISSUE TITLE
what's the problem of this?

### ISSUE THREAD

**Issue by rpzxjp** [ROIcoin/ROIcoin#57]
![2018-03-13 5 08 11](https://user-images.githubusercontent.com/37070416/37332402-920ca128-26e1-11e8-99c4-f527e77c9862.png)
What's the problem? I can't mine a coin today?

**Comment by ghobson2013** [comment]
optiminer owns that pool, his pool as been stuck since yesterday, other users have sent him a message. Suprnova pool still works.

**Comment by rpzxjp** [comment]
Thank you ,ghobson2013, how can I change my pool to Suprnova?

**Comment by ghobson2013** [comment]
https://roi.suprnova.cc/index.php?page=gettingstarted

**Comment by rpzxjp** [comment]
Should I wait for optimizer? It is a little complicate for me to change a pool.
