### ISSUE TITLE
Extremely high fee on some transactions

### ISSUE THREAD

**Issue by startsts** [ROIcoin/ROIcoin#58]
Hy everyone, any idea why wallet send transactions with high fees, example:
{'confirmations': 3497, 'time': 1522168120, 'fee': Decimal('23.02386737'), 'timereceived': 1522168120, 'blockindex': 1, 'txid': 'ab70a403a245d2f9cf438b50c5ec8f6d447e6db598d0c9054645277c4c070067', 'walletconflicts': [], 'amount': Decimal('-2413.99900000'), 'vout': 0, 'blocktime': 1522168176, 'blockhash': '0000001e7a637bd67a0e0c904b7959a9958338d6333db549904d04631ac79b35', 'category': 'send', 'address': 'RAsHzfFDsxsCxkCZRugx3MFLTGGd9iFaet', 'account': ''}

{'confirmations': 25, 'time': 1522680742, 'fee': Decimal('82.82808335'), 'timereceived': 1522680742, 'blockindex': 1, 'txid': 'e627fb1f81ee550621d81c0aaf658bbfe5fa79e30c004e18a74169492c11fd6f', 'walletconflicts': [], 'amount': Decimal('-23795.37880385'), 'vout': 0, 'blocktime': 1522680770, 'blockhash': '0000003cb012100eb379981ea07242543d290196168ea4976b205a0f28fab11a', 'category': 'send', 'address': 'RC773ouZN4QBNkjT1ED4YgVsHhCB6JidJ8', 'account': ''}

both transactions were sent using "sendtoaddress ADR AMOUNT"

getinfo shows low fees:
"paytxfee" : 0.00010000,
"relayfee" : 0.00005000

**Comment by ghobson2013** [comment]
Hi can you send me the output of the following from the node you used to send/receive coins, 
I would like to see output of
getinfo , getpeerinfo , getmempoolinfo  and   getrawmempool true
Thanks.

**Comment by startsts** [comment]
ROIcoin-cli getinfo
{
    "version" : 1010600,
    "protocolversion" : 250040,
    "walletversion" : 60000,
    "balance" : 261868.87104731,
    "blocks" : 85991,
    "timeoffset" : 0,
    "connections" : 112,
    "proxy" : "",
    "difficulty" : 0.01212744,
    "testnet" : false,
    "keypoololdest" : 1521395697,
    "keypoolsize" : 101,
    "paytxfee" : 0.00010000,
    "relayfee" : 0.00005000,
    "errors" : "WARNING: check your network connection, 77 blocks received in the last 4 hours (120 expected)"
}

edited out for readability

**Comment by ghobson2013** [comment]
Hi  startsts , 

Just a quick update, i have been able to reproduce the issue in my lab, and can confirm there
is a bug with fee calculation. This issue is also in the original code of Hodlcoin which as you know we forked last year. I am consulting with their dev's to see how to proceed with a fix.

As far as I can tell the problem is the accumulated interest an input earns every block is being used as a fee when sending coins. The code usually selects coin control entries automatically, so depending on when it was the last time you used that coin control entry the fee will be higher ( since older age means more interest earned ).  This means the fee will never be more than the earned interest of a single coin control input entry. 

As soon as i have a working solution for this issue, I will let you know.
//Gary

**Comment by ghobson2013** [comment]
For Reference, https://github.com/HOdlcoin/HOdlcoin/issues/126 was created.

**Comment by ghobson2013** [comment]
Hi startsts , 

After talking with the lead Hodlcoin developer (FreeTrade) , we both concluded that this is a display problem with gettransaction() RPC call. The fee you see is not the coins consumed, there is code preventing absurd high fee's > 0.1 in the consensus. The block explorer uses gettransaction() rpc call so it has the same display issue.  We will work on a fix for the gettransaction() RPC call.

**Comment by startsts** [comment]
Hi, thanks for this investigation.   It's strange, I talked about that issue since I found a balance leaking at CryptoHub (wallet balance becomes lower than summary balance of users at platform database),  I need time to check

**Comment by ghobson2013** [comment]
Don't forget your coins earn interest on every block while sitting in a wallet and not being locked in a term deposit. Since your not passing those on to the users , I assume this might be your difference in balance ?

**Comment by startsts** [comment]
You mean pos?  Yes I noticed some generated transactions (pos stakes),  but how I said balance is leaking,  means CryptoHub goes to losses, not to profits

**Comment by ghobson2013** [comment]
How do you calculate the balance ? , this bug means the fee returned in gettransaction() rpc call is in correct. ( the fee can never be > 0.1 coin )

**Comment by startsts** [comment]
I get balance from "getinfo" method,  it also returns incorrect value?

**Comment by ghobson2013** [comment]
Hi startsts ,

FreeTrade's fix for https://github.com/HOdlcoin/HOdlcoin/issues/126 has been integrated into our development branch, and is ready for you to test. My initial tests look good.
Do you need me to provide binaries, if yes for which platform ?

//Gary

**Comment by startsts** [comment]
better if you say me what lines of code to change and I recompile daemon

**Comment by ghobson2013** [comment]
If you click on the commit line  above it shows you this info :) here is the direct link
https://github.com/ROIcoin/ROIcoin/commit/b2a0a04ee743344090b58587adeca088e0355dd0

**Comment by startsts** [comment]
recompiled daemon,  now it shows fees normally. thanks, this issue can be closed

**Comment by ghobson2013** [comment]
thankyou for testing, this will be included in the next official wallet release.
