### ISSUE TITLE
Block sync issues

### ISSUE THREAD

**Issue by cbiest** [ROIcoin/ROIcoin#60]
Hello my fellow alt coin miners,
I am literally getting massive headaches because I have 300,000 roi coins but one day my roi wallet just desided it wanted to go into limbo when I downloaded the latest version of the roi wallet.
I am running on v1.1.6.000 (64-bit) of the roicoin wallet.
I pinged ping 144.76.174.21, the ROI node and it was able to connect to it.
I deleted everything except my roi wallet.dat file, reinstalled the wallet and no cigar. It won't budge past 2 weeks syncing that is. It kinda makes me a little mad because so many people are actually mining coins now which cranks the difficulty up. I just want this to work.
PLEASE help,
Yours trully,
cbiest

**Comment by ghobson2013** [comment]
Hi
What wallet version were you on when the trouble started, and when did this happen ?

Procedure to resync the blockchain:
Dowload from release folder the bootstrap-1532018.zip file and unzip it in %APPDATA%/roaming/ROIcoin folder.
backup your wallet.dat , remove your blocks and chainstate subfolder from %APPDATA%/roamin/Roicoin folder and start ROIcoin-qt with the -loadblock=bootstrap-1532018.dat flag. You can reach us on slack or discord if you need help.
Note: the -loadblock flag expects you to provide full path to the bootstrap file ! It is a startup flag not a console command.

if you already did this and see the wallet stuck then please provide me with your debug.log file. compress it and attach it here, do not paste any of its content in here.

2nd please provide me with your ROIcoin address.

Regards.

**Comment by cbiest** [comment]
I am running on v1.1.6.000 (64-bit) of the roicoin wallet. This started happening 2  weeks ago. It started when I downloaded this new wallet. BTW Disasterfaster on discord sent me here. Me and him looked at the debug file. We also did some stuff with the cmd pronpt. We did netstat -a -n and all the ports are all clear.

**Comment by DisasterFaster** [comment]
I suspect an issue with his school network creating issues connecting for synchronizing on the required port.

**Comment by cbiest** [comment]
I don't believe it is the network of my school because I created a wallet on my laptop and it was synced after around 2 hours.
[debug.log](https://github.com/ROIcoin/ROIcoin/files/1968199/debug.log)

**Comment by cbiest** [comment]
My main computer is having the problem though.

**Comment by ghobson2013** [comment]
Thanks for the debug log so here is what I see:

You were running an obsolete wallet v1.1.2 all the way up to 21 April 2018, despite the fact that we released a mandatory hard fork release v1.1.4 on 21 Feb 2018 and v1.1.6 on 04 March 2018.

On 19 April 2018 while you were on v1.1.2 your wallet was not synced up, i see block 94156 while the network was at 94867. This makes me think you were on the wrong chain. On 21 April 2018 when you upgraded to v1.1.6  , your wallet was not synced up.

From the start of the log you can see many "invalid header received" errors, which is the consequence of not following our advice when we released v1.1.4 and told people you will need to re-sync your blockchain from scratch ( using a provided bootstrap file ).

So to get out of this issue, you need to re-sync from scratch using the provided bootstrap file as instructed earlier.

Since you have been running for such a long time on the wrong chain, you will likely have lost the coins you mined since Feb 21 and any deposits based on those coins found on wrong chain.

**Comment by cbiest** [comment]
What about my wallet.dat file? I thought that was how you saved the coins? I made a backup of my wallet.dat file before this went down. 
You keep refering back to " Dowload from release folder the bootstrap-1532018.zip file and unzip it in %APPDATA%/roaming/ROIcoin folder." where on the website is this bootstrap file?

**Comment by ghobson2013** [comment]
Its available from all our official download pages
https://github.com/ROIcoin/ROIcoin/releases/download/v1.1.6.000/bootstrap-1532018.zip
and
https://roi-coin.com/downloads/bootstrap-1532018.zip

**Comment by cbiest** [comment]
That is no where to be found on roi-coin.com.

**Comment by cbiest** [comment]
"Dowload from release folder the bootstrap-1532018.zip file and unzip it in %APPDATA%/roaming/ROIcoin folder."
Do you mean put the unzipped file in the app data roi coin folder?

**Comment by cbiest** [comment]
ok I put the bootstrap and the wallet.dat file  in the same folder as the roi folder. what else do I need to do?

**Comment by ghobson2013** [comment]
backup your wallet.dat , remove your blocks and chainstate subfolder from %APPDATA%/Roaming/ROIcoin folder. Also delete the peers.dat file in %APPDATA%/Roaming/ROIcoin

start ROIcoin-qt with the -loadblock=C:\xxxx\yyyy\bootstrap-1532018.dat flag

Note: the -loadblock flag expects you to provide full path to the bootstrap file ! It is a startup flag not a console command

The debug.log will then show progress on the block loading, you need to wait till your wallet matches the latest block as seen on the block explorer https://roi-coin-blockexplorer.roi-coin.com/

**Comment by cbiest** [comment]
start ROIcoin-qt with the -loadblock=C:\xxxx\yyyy\bootstrap-1532018.dat flag how does that work?

**Comment by cbiest** [comment]
I know u think you know everything but "%APPDATA%/Roaming/ROIcoin folder. Also delete the peers.dat file in %APPDATA%/Roaming/ROIcoin" is not where the roi coin directory is on my computer.

**Comment by cbiest** [comment]
This is solved but not because of u @ghobson2013 . You only confused me further.
