### ISSUE TITLE
Wallet is shutting down intermittently

### ISSUE THREAD

**Issue by JonathanLS** [ROIcoin/ROIcoin#64]
my wallet is shutting down intermittently

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2018-05-19 18:30:25 *** System error while flushing: CDB: Error -30974, can't open database 
2018-05-19 18:30:32 ERROR: ProcessNewBlock: ActivateBestChain failed
2018-05-19 18:30:32 addcon thread interrupt
2018-05-19 18:30:32 opencon thread interrupt
2018-05-19 18:30:32 msghand thread interrupt
2018-05-19 18:30:32 net thread interrupt
2018-05-19 18:30:32 scheduler thread interrupt
2018-05-19 18:30:32 Shutdown: In progress...
2018-05-19 18:30:32 RPCAcceptHandler: Error: Operation canceled
2018-05-19 18:30:32 StopNode()
2018-05-19 18:30:32 UPNP_DeletePortMapping() returned: 0
2018-05-19 18:30:32 upnp thread interrupt
2018-05-19 18:30:33 *** System error while flushing: CDB: Error -30974, can't open database 
2018-05-19 18:30:38 CDBEnv::EnvShutdown: Error -30974 shutting down database environment: DB_RUNRECOVERY: Fatal error, run database recovery
2018-05-19 18:30:38 Shutdown: done
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Wallet: ROIcoin Core version v1.1.6.000 (64-bit)
OS: DISTRIB_DESCRIPTION="Linux Mint 18.2 Sonya"

**Comment by ghobson2013** [comment]
hi can you tell me which binary are you using ? did you compile it yourself on mint ?
error -30974 is DB_VERSION_MISMATCH

**Comment by JonathanLS** [comment]
@ghobson2013 where do I check which binary I am using? I only did the download of the .zip file from the ROI Server and executed the ROIcoin-qt file. This is the second time I install the wallet 1.1.6 on Linux (I was using a Windows version, but my hard disk has damaged). At first time I used the default path. The second time I chose a customized path with access only for root user. I think this is the problem. Should I reinstall it using default path?

**Comment by ghobson2013** [comment]
Hi , 
What do you mean with "my hard disk has damaged" ? and what did you do to fix it ?
The error you provided says "Linux Mint 18.2 Sonya"  , there is no zip for linux, so what exactly did you use ?

**Comment by JonathanLS** [comment]
@ghobson2013 Gary, I'm sorry, I will try to be more clear. I am running the wallet on Linux Mint 18.2 Sonya, where the error happened. I was executing the wallet in a laptop running Windows, but its hard disk had bad blocks and therefore the Windows stopped. I had the wallet installed in other computer running Linux, so I used that machine again and I decided reinstall the wallet using the file ROIcoin-1.1.6-linux64.tgz (and I had a backup wallet.dat file), but instead of use the default path I used a customized path to put the datadir where I need privilege of root user to access it. I deleted the blocks and chaistate folders, put the wallet.dat from the backup into the datadir and executed the ROIcoin-qt. It synced and everything seemed work fine until the error happen. But as I said before, the error is intermittent.

**Comment by ghobson2013** [comment]
Hi, when you open up the debug window, what version shows up for berkleydb , is it 4.8 ?
our tgz file was build on Ubuntu 16.04 LTS , which linux mint 18.2 is also based of , so in theory they should be compatible. It is possible the windows dat format isn't fully compatible with the linux one. Was it a 64 bit windows OS ?  In any case It might be better to transfer the keys to a new fresh wallet.dat and see if that is more stable. So keep a backup of your wallet.dat , then run dumpwallet rpc command in the debug console , it will export all your keys. Shutdown the wallet rename wallet.dat to wallet.dat.old then start the wallet again. That will create a new wallet.dat, now run importwallet RPC command,  that may take time as for each key the wallet scans the blockchain for your transactions.

**Comment by JonathanLS** [comment]
@ghobson2013 It shows up version Berkeley DB 4.8.30: (April  9, 2010). Yes, It was a  bit Windows OS. OK, I will execute these procedures on next time the wallet accidentally shutdowns, since my wallet is up since Sun May 20 22:15:25 2018. While I am writing are Mon May 21 08:19 and untill now it is working fine.
