### ISSUE TITLE
RIOcoin stuck at 143707

### ISSUE THREAD

**Issue by petvanbev** [ROIcoin/ROIcoin#67]
My ROIcoin wallet, updated to v1.1.7.000 (64-bit), stuck at 134707, despite the 'fix" posted on their website.
Using Win 7, SP1 
Any ideas?

Thanks

**Comment by ghobson2013** [comment]
just resync from scratch it only takes 30-40 mins or so.
stop the wallet, 
backup your wallet.data, delete all other files in %APPDATA%/Roaming/ROicoin except your wallet.dat , then restart wallet.

**Comment by petvanbev** [comment]
Thanks,

The fix on the ROIcoin website seems to have took. Wallet topped up to
what was indicated in the block explorer.

If it acts up again, I will try your advice..

Peter

On Sat, 14 Jul 2018 01:41:53 -0600, Gary Hobson <notifications@github.com>  
wrote:

> just resync from scratch it only takes 30-40 mins or so.
> stop the wallet,
> backup your wallet.data, delete all other files in  
> %APPDATA%/Roaming/ROicoin except your wallet.dat , then restart wallet.
>


-- 
Using Opera's revolutionary e-mail client: http://www.opera.com/mail/
