### ISSUE TITLE
Lost Coins

### ISSUE THREAD

**Issue by xrtmns** [ROIcoin/ROIcoin#69]
Hello to the community. I sent about 2000 ROI from suprnova to my wallet (1.1.6) about a week before and never come. The transaction is confirmed, I found it on the explorer. Any help? And coins are locked in my wallet, are safe?

**Comment by ghobson2013** [comment]
Hi 
Can you provide the transactionID ?  
Did you check that the wallet is in sync with the block explorer ? in otherwords that the last blocknr shown in the debug window matches the blockexplorer last reported block give or take 10 blocks ?
Are you on discord, best way to handle these type of issues is via direct messages to me.
Regards,

**Comment by xrtmns** [comment]
Sorry, I don't have discord account. The block that is synched to my wallet is 169840 and the wallet shows it is synchronized. The latest block on the explorer at the same time is 172788. The TX ID is: 
9916c43125dbe1e063b7f9ef0a5615da6ad74489c068e56c41d6898f0603934e

**Comment by ghobson2013** [comment]
can you provide me your debug.log ( zip compressed) ?
did you just blindly copy the content of https://roi-coin.com/downloads/blockchain-11072018.zip ? you need to actually get rid of the old blocks/chainstate folders first.

you could try starting the wallet with the following startup flags  -rescan -zapwallettxes=2
it will rescan the chain for your transactions.

The other scenario would be to run dumpwallet c:\myprivatekeys,txt   then stop the wallet rename wallet.dat to wallet.old... restart it will make a new wallet.dat see if it syncs,  If it does you can then use importwallet c:\myprivkey.txt   to re-import your keys.

**Comment by xrtmns** [comment]
Sorry for my late response, I didn't have enough time to spend in previous weeks. Finally I download a new version of wallet(V 1.2.0.0.0) and I copy/paste the wallet.dat in there and now it is fully synchronized. It works fine. Anyway, thanx for helping me.
