### ISSUE TITLE
listtermdeposit * does not work, shows "Invalid account name"

### ISSUE THREAD

**Issue by TheTDD** [ROIcoin/ROIcoin#75]
It is not possible to see all term deposits using daemon 1.1.17

- `listtermdeposits *` displays "Invalid account name"

As soon deposits is the unique feature of ROIcoin I believe this function is important. As urgent update please consider to change the code in `rpcwallet.cpp` (function `listtermdeposits`) to be able at least show all deposits:

```
std::vector<COutput> termDepositInfo;

    if (params[0].get_str() == "*") {
        termDepositInfo = pwalletMain->GetTermDepositInfo();
    } else {
        string strAccount = AccountFromValue(params[0]);
        termDepositInfo = pwalletMain->GetTermDepositInfo(strAccount);
    }
```

instead of 

```
string strAccount = AccountFromValue(params[0]);
    std::vector<COutput> termDepositInfo = pwalletMain->GetTermDepositInfo(strAccount);
```

**Comment by ghobson2013** [comment]
the default account name is "" not "*"

**Comment by TheTDD** [comment]
if use default account '' you will not see deposits made with other accounts

help shows:

```
listtermdeposits "fromaccount" 

Arguments:
1. "fromaccount"       (string, required) The name of the account to list term deposits from. May be the default account using "" use "*" for all.
Result:
"term deposits "  (string array)

Examples:
> roicoin-cli listtermdeposits  "*"
> curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "listtermdeposits", "params": [ "gary"] }' -H 'content-type: text/plain;' http://127.0.0.1:3376/
```
as you see "*" should be supported

**Comment by ghobson2013** [comment]
"*" isn't an account name, if you want to see the term deposits of others you have to enumerate them.
so do "ROIcoin-cli listaccounts" first and then for each entry grab the key(account name) and run listtermdeposits on them.

**Comment by ROIcoin** [comment]
Issue #75 - function `listtermdeposits` to show all deposits.  Incorporated into Development branch for future release.  Close.

rpcwallet.cpp ln 886 

    std::vector<COutput> termDepositInfo;

	if (params[0].get_str() == "*") {
	   termDepositInfo = pwalletMain->GetTermDepositInfo(); 
	} else {
	   string strAccount = AccountFromValue(params[0]);
	   termDepositInfo = pwalletMain->GetTermDepositInfo(strAccount);
        }

Replaced:

string strAccount = AccountFromValue(params[0]); std::vector<COutput> termDepositInfo = pwalletMain->GetTermDepositInfo(strAccount);
