### ISSUE TITLE
./ROIcoin-qt: error while loading shared libraries: libboost_system.so.1.62.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by aaronllowe** [ROIcoin/ROIcoin#77]
Hello,
I have been getting this error when I try to launch ROIcoin-qt. I have made sure that I have installed this library, but I have no luck getting it to work. Please help me!

**Comment by ghobson2013** [comment]
your missing dependencies , in this case libboost_system library
if your not familiar with how to resolve dynamic library dependencies, run the "ldd" command against ROIcoin-qt binary to see what dependencies your missing, you probably just need to do 
sudo apt-get install libboost-all-dev

**Comment by aaronllowe** [comment]
It looks like I still don't have most of the libboost stuff, even after I tried sudo apt-get install libboost-all-dev. Here is the stuff I'm missing. 
```
libdb_cxx-4.8.so => not found
libssl.so.1.0.0 => not found
libminiupnpc.so.10 => not found
libcrypto.so.1.0.0 => not found
libprotobuf.so.10 => not found
libboost_system.so.1.62.0 => not found
libboost_filesystem.so.1.62.0 => not found
libboost_program_options.so.1.62.0 => not found
libboost_thread.so.1.62.0 => not found
libboost_chrono.so.1.62.0 => not found
```

**Comment by ghobson2013** [comment]
what OS are you on ?

**Comment by ghobson2013** [comment]
I will assume you are on ubuntu18.04 LTS and that you are trying the ROIcoin-qt-ubuntu18 binary
, you will need the following libraries:

sudo apt-get install libssl1.0-dev 
sudo add-apt-repository ppa:bitcoin/bitcoin
sudo apt-get update
sudo apt-get install libdb4.8-dev libdb4.8++-dev
sudo apt-get install libminiupnpc-dev libzmq3-dev libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler libqrencode-dev

sudo apt-get install libboost-all-dev  should have installed all boost related libraries.

**Comment by aaronllowe** [comment]
I'm on Ubuntu 19.04.

**Comment by aaronllowe** [comment]
Ok, thanks, I just decided to do it on my Mac. Thanks for the help!
