### ISSUE TITLE
Can I fork ROIcoin to make my own coin?

### ISSUE THREAD

**Issue by aaronllowe** [ROIcoin/ROIcoin#78]
Hello,
I really love this project, and was wondering how to fork this project to create my own coin. I have no experience in any way with cryptocurrency and don't know where to change all the config and stuff. Could someone write a guide about it? I really love this project, and its great.

**Comment by ghobson2013** [comment]
This project is open-source, off-course you can fork and do your own coin. We only ask that you acknowledge the contributions we made to the project. ( usually in the about section or copyright notices ).  Thanks for asking.

**Comment by aaronllowe** [comment]
Ok great! Could you point me in the right way? I’m looking for the config file.

**Comment by ghobson2013** [comment]
if you want to add ack in the gui splash screen its in https://github.com/ROIcoin/ROIcoin/blob/master/src/qt/splashscreen.cpp
if you want to add ack to the source header files, any of them will have ack's for previous teams, so just add another line.
// Copyright (c) 2014-2019 The ROIcoin developers

Thanks.

**Comment by PWRcoin** [comment]
Here is a nice primer to get you started.  We do not support Dillinger in any way, it is simply a resource on the basics.  Be prepared to do a lot of google searches to find your own answers.

http://dillingers.com/blog/2015/04/18/how-to-make-an-altcoin/

Use Ubuntu for your dev boxes.
