### ISSUE TITLE
block sync issue with ROIcoin v1.2.0

### ISSUE THREAD

**Issue by rodrigoreloaded** [ROIcoin/ROIcoin#79]
I'm 50 weeks trying to update my roi wallet, but the wallet just say "No server available".
Did i lost all my roi coins?

**Comment by ghobson2013** [comment]
What wallet version are you on ? What is your ROI address, you can always check on the explorer how many coins are seen by the block chain.
Can you zip up and send me your debug.log ?

**Comment by rodrigoreloaded** [comment]
My Wallet is 1.2.0.000 Version
my wallet adress: RRymYC4WBsYRP6wj9rnwEGYa9gZQh6R9SN

My debug.log file
https://www.sendspace.com/file/eyhjyk

**Comment by ghobson2013** [comment]
Hi Rodrigo , please try the following procedure.
1 - stop the wallet, and backup your wallet.dat to a safe place.
2 - goto the D:\util\Executaveis\RoiCoin Directory
3 - delete all files except wallet.dat and ROIcoin.conf(if it exist)
4 - download this blockchain bootstrap zip file (https://github.com/ROIcoin/ROIcoin/releases/download/v1.2.0.000/blockchain-12-august-2019.zip ) and unzip it in the D:\util\Executaveis\RoiCoin directory.
5 - start wallet back up , and tell me if its syncing ...

**Comment by rodrigoreloaded** [comment]
Now seems to be working!

Thanks very much! :D

**Comment by ghobson2013** [comment]
very good, closing this issue.
