### ISSUE TITLE
ROIcoin-QT / Wrong roicoin.icns icon

### ISSUE THREAD

**Issue by TheTDD** [ROIcoin/ROIcoin#9]
There is old HODLcoin squirrel icon roicoin.icns in /src/qt/res/icons directory.
If building ROIcoin-QT for OSX the Icon of application is created the same as for HODLcoin.

Please replace the icon file with ROIcoin's logo.

**Comment by ROIcoin** [comment]
Hello - I have copied over the updated from the Dev branch to the Master.  Unfortunately, I do not have a Mac, to verify the image.  Will try to find some graphics software to verify, before closing issue.

Thank you.

**Comment by ghobson2013** [comment]
Hi , 
Sorry about that, i had submitted the correct icns file in the dev branch and forgot to submit it in the master branch , this was the commit for it in the dev branch https://github.com/ROIcoin/ROIcoin/commit/b100942bebe517bf4c11bf384017d8cfb86916ba

**Comment by ghobson2013** [comment]
Can you please download the beta version in the release folder and let me know if you see the hodl icon ?

**Comment by ghobson2013** [comment]
fixed and tested on v1.1.1
